# Enable deep sleep support (default: no)
CONFIG_ZMK_SLEEP=y

# Inactivity time before entering idle/sleep state (defaults: 30000/90000)
CONFIG_ZMK_IDLE_TIMEOUT=1200000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# Increase the keyboard's wireless range (default: no)
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Global debounce time for key press/release (defaults: -1/-1, typeractive presets: 1/10)
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10

# Enable the general pointing/mouse functionality
CONFIG_ZMK_POINTING=y

# Enable ZMK Studio for realtime keymap updates
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
